services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app@db:5432/appdb
      JWT_SECRET: devsecret
      JWT_EXPIRES_MIN: "60"
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      - db
    ports:
      - "8000:8000"
  web:
    build: ./apps/web
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - api
    ports:
      - "5173:5173"
volumes:
  db_data:
