services:
  postgres:
    image: pgvector/pgvector:0.7.4-pg16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    external: false
